version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dish2calories-api
    command: bash -lc "python inference.py"
    environment:
      # Make the API discoverable by the UI inside the compose network
      API_HOST: 0.0.0.0
      API_PORT: 8000
      # Streamlit may call this if you use it in code
      API_URL: "http://api:8000"
      # Uncomment if you rely on Torch CUDA checks, etc.
      # NVIDIA_VISIBLE_DEVICES: "all"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped
    gpus: all  # requires NVIDIA Container Toolkit

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dish2calories-ui
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      STREAMlit_SERVER_HEADLESS: "true"
      # Point UI to API service name in compose network
      API_URL: "http://api:8000"
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - api
    restart: unless-stopped
    gpus: all  # requires NVIDIA Container Toolkit

networks:
  default:
    name: dish2calories-net

